// `.product/quality/debt.json`: the open technical debt, written only by the core (D30).
// It holds live items, not history: a resolved item is removed and git keeps the rest.
// `TDR.md` beside it is the human view, regenerated on every write.
import fs from "node:fs";
import path from "node:path";
import { RuleError } from "./cli.mjs";
import { writeAtomic } from "./files.mjs";
import { productPath } from "./paths.mjs";

export const PRIORITIES = ["high", "medium", "low"];
export const STATES = ["confirmed", "not-revalidated"];
export const EMPTY_DEBT = Object.freeze({ items: [] });

const FIELDS = ["id", "title", "priority", "state", "scope", "evidence", "impact", "origin", "confirmed"];
const TEXT_FIELDS = ["title", "scope", "evidence", "impact"];
// The source of a piece of evidence: a spec report, or the quality check of one project.
export const SOURCE = /^(?:S\d{4}-[a-z0-9-]+\/(?:verification|qualification)\.md|quality:[a-z0-9]+(?:-[a-z0-9]+)*)$/;

export const debtFile = (root) => productPath(root, "quality", "debt.json");
export const viewFile = (root) => productPath(root, "quality", "TDR.md");
export const debtText = (debt) => `${JSON.stringify(debt, null, 2)}\n`;

const isObject = (value) => value !== null && typeof value === "object" && !Array.isArray(value);

/** Throw on the first schema violation; return the value when valid. */
export function validateDebt(debt) {
  if (!isObject(debt) || !Array.isArray(debt.items) || Object.keys(debt).some((key) => key !== "items")) throw new RuleError("debt.json must be { \"items\": [ … ] }.");
  const ids = new Set();
  for (const item of debt.items) {
    const where = `debt.json ${item?.id ?? "item"}`;
    if (!isObject(item)) throw new RuleError(`${where} must be an object.`);
    const extra = Object.keys(item).find((key) => !FIELDS.includes(key));
    if (extra) throw new RuleError(`${where} has an unknown key: ${extra}`);
    if (!/^D\d{4}$/.test(item.id ?? "") || ids.has(item.id)) throw new RuleError(`${where} needs a unique D ID.`);
    ids.add(item.id);
    for (const key of TEXT_FIELDS) if (typeof item[key] !== "string" || !item[key].trim() || /[\r\n]/.test(item[key])) throw new RuleError(`${where} ${key} must be one non-empty line.`);
    if (!PRIORITIES.includes(item.priority)) throw new RuleError(`${where} priority must be ${PRIORITIES.join(", ")}.`);
    if (!STATES.includes(item.state)) throw new RuleError(`${where} state must be ${STATES.join(", ")}.`);
    if (!/^(?:S\d{4}|scan)$/.test(item.origin ?? "")) throw new RuleError(`${where} origin must be a spec ID or scan.`);
    if (!isObject(item.confirmed) || !SOURCE.test(item.confirmed.source ?? "") || !item.confirmed.at || !item.confirmed.commit) throw new RuleError(`${where} confirmed needs at, commit, and a source.`);
  }
  return debt;
}

export function readDebt(root) {
  const file = debtFile(root);
  if (!fs.existsSync(file)) throw new RuleError(`${path.relative(root, file)} is missing; run aiddbot init.`);
  let value;
  try { value = JSON.parse(fs.readFileSync(file, "utf8")); } catch (error) { throw new RuleError(`debt.json is not valid JSON: ${error.message}`); }
  return validateDebt(value);
}

const rank = (item) => `${PRIORITIES.indexOf(item.priority)}${item.id}`;

export function renderView(debt) {
  const lines = ["# Technical debt register", "", "Open debt, highest priority first. Generated by `aidd debt` from `debt.json`; do not edit."];
  if (debt.items.length) lines.push("");
  for (const item of [...debt.items].sort((a, b) => rank(a).localeCompare(rank(b)))) {
    lines.push(`- **${item.id}** ${item.priority}, ${item.state}: ${item.title} — ${item.scope}. ${item.evidence}; ${item.impact}. (${item.origin === "scan" ? "found by a scan" : `from ${item.origin}`}; last confirmed ${item.confirmed.at.slice(0, 10)} by ${item.confirmed.source})`);
  }
  return `${lines.join("\n")}\n`;
}

/** Write the register and regenerate its view. */
export function writeDebt(root, debt) {
  validateDebt(debt);
  writeAtomic(debtFile(root), debtText(debt));
  writeAtomic(viewFile(root), renderView(debt));
}
