// `.product/specs/README.md`: a human view of what the product does, one line per shipped
// spec grouped by domain (D26). Only the core writes it, regenerated whole on every release.
import fs from "node:fs";
import path from "node:path";
import { writeAtomic } from "./files.mjs";
import { read } from "./frontmatter.mjs";
import { shippedSpecDirs, specsDir } from "./spec.mjs";

export const INDEX = "README.md";

/** One entry per shipped spec: its ID, folder, domain, and the title of its heading. */
function entries(root) {
  return shippedSpecDirs(root).map((dir) => {
    const text = fs.readFileSync(path.join(dir, "spec.md"), "utf8");
    const key = path.basename(dir);
    const title = /^# \S+ — (.+)$/m.exec(text)?.[1].trim() ?? key;
    return { id: key.slice(0, 5), key, domain: read(text, "Spec").domain || "unclassified", title };
  });
}

export function renderIndex(root) {
  const byDomain = Map.groupBy(entries(root), (entry) => entry.domain);
  const lines = ["# Specs", "", "What the product does, one line per shipped spec. Generated by `aidd release`; do not edit."];
  for (const domain of [...byDomain.keys()].sort()) {
    lines.push("", `## ${domain}`, "", ...byDomain.get(domain).map((entry) => `- [${entry.id}](${entry.key}/spec.md) ${entry.title}`));
  }
  return `${lines.join("\n")}\n`;
}

/** Regenerate the index and return its path. */
export function writeIndex(root) {
  const file = path.join(specsDir(root), INDEX);
  writeAtomic(file, renderIndex(root));
  return file;
}
